### ISSUE TITLE
[Feature request] Add a domain filter

### ISSUE THREAD

**Issue by kissifrot** [redirectionio/proxy-symfony#1]
Hello,

RIO's proxy is installed on an application which serves different domains.
One of them generates a lot of noise due to a notification features which makes a lot of HTTP calls.

Would it be possible to filter a specific domain ?

**Comment by lyrixx** [comment]
@kissifrot Thanks. This has been fixed in 60e605f9241e08c69a86a876ae34da8d278aa8d5

BTW, I strongly suggest you to upgrade the bundle to v0.2.1  release to get this new features, and to get ride of the agent configuration. But you will have to configure the project key in the symfony application. Warning: this is not the same key in (dev + staging) vs (prod)

**Comment by kissifrot** [comment]
Thanks!
